#SPRING
spring.application.name=knowledgeuniverse
server.port=${API_PORT:8080}
server.address=0.0.0.0
spring.session.timeout.seconds=300
#server.servlet.contextPath=/knowledgeuni
#todo delete last 2 lines if bugged :
spring.data.elasticsearch.repositories.enabled=true
spring.elasticsearch.uris=http://localhost:9200
#todo when security gets enabled :
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=your_password

#DATA SOURCE
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/knowledgeuni?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
#spring.session.jdbc.initialize-schema=always

#HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring,jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#VIEW ENGINE
spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.cache=false

#MESSAGES
spring.messages.encoding=UTF-8

#ELASTICSEARCH
elasticsearch.host=${ES_HOST:localhost}
elasticsearch.port=${ES_PORT:9200}
elasticsearch.userName=
elasticsearch.password=
#elasticsearch.userName=${ES_USERNAME:}
#elasticsearch.password=${ES_PASSWORD:}

# DOCUMENT STORAGE - MINIO
spring.minio.url=http://${MINIO_HOST:localhost}:9000
spring.minio.bucket=${MINIO_BUCKET:knowledgeuni-file-items}
spring.minio.access-key=${MINIO_ACCESS_KEY:ROOTUSER}
spring.minio.secret-key=${MINIO_SECRET_KEY:CHANGEME123}

## LOGGING
## Log file configuration
#logging.file.name=logstash-ingest-data/application.log
##logging.level.com.example=DEBUG #(optional)


#SPRING MVC
#spring.mvc.static-path-pattern=/**
#spring.resources.static-locations=
#spring.mvc.view.prefix: /WEB-INF/jsp/
#spring.mvc.view.suffix: .jsp
